version: "3.6"

services:
  # Based on https://github.com/firecat53/dockerfiles/tree/master/openvpn-client-pia
  # pia_port port is writting in /home/docker/pia/pia_port
  # before building :
  #   chmod 655 port_forward.sh
  vpn:
    container_name: vpn
    image: openvpn-client
    network_mode: bridge
    cap_add:
      - net_admin
    devices:
      - "/dev/net/tun"
    volumes:
      - /home/docker/openvpn:/config
      - /home/docker/pia:/var/run/pia/
    ports:
      - 9117:9117/tcp
      - 8112:8112/tcp
    expose:
      - "9117"
      - "8112"

  traefik:
    image: traefik:latest    
    command: --docker --docker.domain=<mydomain here>
    ports:
      - 80:80
      - 443:443
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    labels:
      - "traefik.frontend.rule=Host:<mydomain here>"
      - "traefik.port=8080"
    container_name: traefik
    restart: always

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    depends_on:
      - vpn
    volumes:
      - /home/docker/jackett/config:/config
      - /mnt/downloads:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1001
      - PGID=1001
    network_mode: "service:vpn"
    restart: always
    
  # Based on : https://github.com/firecat53/dockerfiles/tree/master/deluge
  deluge:    
    image: deluge:latest
    container_name: deluge
    depends_on:
      - vpn
    volumes:
      - /home/docker/deluge/config:/config
      - /home/docker/pia:/var/run/pia/
      - /mnt/downloads:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1001
      - PGID=1001      
    network_mode: "service:vpn"
    restart: always

  vpn_nginx:    
    image: nginx:alpine
    container_name: vpn_nginx
    depends_on:
     - jackett
     - deluge    
    links:
     - vpn:jackett
     - vpn:deluge
    volumes:
      - /home/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
     - "traefik.jackett.backend=jackett_nginx"
     - "traefik.jackett.frontend.rule=Host:jackett.<mydomain here>"
     - "traefik.jackett.port=8001"
     - "traefik.deluge.backend=deluge_nginx" 
     - "traefik.deluge.frontend.rule=Host:deluge.<mydomain here>"
     - "traefik.deluge.port=8000"
    network_mode: bridge
    restart: always


